### ISSUE TITLE
网友提问

### ISSUE THREAD

**Issue by longer-is-better** [Corezcy/ProtoToJson#1]
https://github.com/bazelbuild/bazel/issues/12748
hello，请问这个问题你最后解决了么？

**Comment by Corezcy** [comment]
> [bazelbuild/bazel#12748](https://github.com/bazelbuild/bazel/issues/12748)
> hello，请问这个问题你最后解决了么？

解决了，中间某一步使用了代码依赖（比如包含.h, .cpp）。转而使用动态库依赖可以解决这个问题。
